<a href="https://colab.research.google.com/github/devyulbae/AIClass/blob/main/Ex)_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Ex
### Numpy import
* 넘파이 사용을 위해 import
* 만약 설치가 안되어 있다면 설치해줍니다.
```
!pip install numpy
```


In [1]:
import numpy as np

## 문제 1: 배열 생성과 기본 연산
### 1.1 크기가 10인 0으로 채워진 배열 생성

In [3]:
# np.zeros
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

### 1.2 배열의 5번째 원소를 1로 설정

In [6]:
# indexing
arr1[4] = 1
arr1

array([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.])

---

### 1.3 10에서 50까지의 정수를 담은 배열 생성

In [9]:
# np.arange
arr2 = np.arange(10,51)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

---

### 1.4 배열 뒤집기

In [13]:
# slicing
arr2_reversed = np.flip(arr2)
arr2_reversed

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

---

### 1.5 3x3 단위행렬 생성

In [14]:
# np.eye
idt_mat = np.eye(3)
idt_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

## 문제 2: 통계

### 2.1 크기가 30인 무작위 정수 배열 생성, 평균 구하기

In [19]:
# randint
rand_arr = np.random.randint(-100, 100, size=30)

print(rand_arr)

[-69  76 -74   9   7 -68 -88 -34  96 -37  25  51   4  43  79 -98  53  20
   4 -88  58 -35  88 -84 -13  71 -11  52  96 -86]


---

### 2.2 5x5 크기의 2차원 배열, 최댓값과 최솟값 찾기

In [24]:
# rand(randint), np.max, np.min
rand_arr_2d = np.random.randint(0,10,size=(5,5))

max_val, min_val = rand_arr_2d.max(), rand_arr_2d.min()
print(rand_arr_2d)
print(max_val, min_val)

[[8 0 0 2 1]
 [5 2 3 7 3]
 [7 3 1 4 4]
 [1 9 5 6 7]
 [5 3 7 4 4]]
9 0


---

## 문제 3: 인덱싱과 슬라이싱

### 3.1 크기가 10인 배열 생성, 4번째에서 8번째 원소를 -1로 설정

In [25]:
# np.ones
arr3 = np.zeros(10)
arr3[3:8] = -1
arr3

array([ 0.,  0.,  0., -1., -1., -1., -1., -1.,  0.,  0.])

---

### 3.2 10x10 크기의 2차원 배열, 안쪽 8x8 추출

In [28]:
arr4 = np.random.randint(10, size=(10,10))

inner_arr4 = arr4[:8,:8]
print(inner_arr4)

[[7 2 4 4 4 5 5 9]
 [3 6 0 0 7 7 2 8]
 [1 3 2 2 3 6 8 5]
 [8 5 8 7 6 5 4 1]
 [0 7 1 4 1 9 1 8]
 [7 0 5 8 1 6 9 0]
 [2 8 1 5 5 1 4 8]
 [0 9 2 2 0 1 4 4]]


---

## 문제 4: 불리언 인덱싱
### 4.1 크기가 10인 무작위 정수 배열 생성

In [32]:
# np.random.randint
rand_arr = np.random.randint(5,15, size=10)
rand_arr

array([ 5, 13,  8,  9,  6,  6, 12,  9, 14,  5])

---

### 4.2 배열에서 8보다 큰 값만 추출

In [ ]:
# 주어진 배열 안에서 arr[arr > 8] 조건에 만족하는 값을 뽑아서 출력해줍니다.

In [33]:
ft_rand_arr = rand_arr[rand_arr > 8]
ft_rand_arr

array([13,  9, 12,  9, 14])

---

## 문제 5: 선형대수
### 5.1 5x5 크기의 무작위 정수 배열 생성

In [39]:
# randint
mat = np.random.randint(5, size=(5,5))
mat

array([[3, 1, 4, 1, 0],
       [1, 4, 2, 2, 0],
       [4, 2, 1, 3, 1],
       [2, 4, 2, 2, 4],
       [1, 4, 4, 1, 3]])

---

### 5.2 역행렬 구하기

In [42]:
# np.linalg.inv(arr)
inverse_mat = np.linalg.inv(mat).round(decimals=2)
inverse_mat

array([[ 2.46,  1.15, -2.77,  3.92, -4.31],
       [ 1.92,  1.31, -2.54,  3.35, -3.62],
       [-1.08, -0.69,  1.46, -2.15,  2.38],
       [-4.  , -2.  ,  5.  , -6.5 ,  7.  ],
       [-0.62, -0.54,  0.69, -0.73,  1.08]])

---

### 5.3 내적 구하기

In [44]:
dot_p = np.dot(mat, inverse_mat).round(decimals=2)
dot_p

# 값이 정확하진 않지만 단위행렬에 근사하는 것을 알 수 있다.

array([[ 0.98,  0.  , -0.01,  0.01, -0.03],
       [-0.02,  1.01, -0.01,  0.02, -0.03],
       [-0.02, -0.01,  0.99,  0.  , -0.02],
       [-0.04,  0.  , -0.02,  1.02, -0.02],
       [-0.04,  0.01, -0.02,  0.03,  0.97]])

---